"""Add Factura and Cliente models

Revision ID: 0e1744db6833
Revises: d203c95a55ef
Create Date: 2024-10-04 19:17:01.619868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e1744db6833'
down_revision = 'd203c95a55ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('detalle_factura')
    op.drop_table('item_factura')
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('estatus',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('estatus',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('total')

    op.create_table('item_factura',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], name='item_factura_factura_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_factura_pkey')
    )
    op.create_table('detalle_factura',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], name='detalle_factura_factura_id_fkey'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name='detalle_factura_producto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='detalle_factura_pkey')
    )
    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='producto_pkey')
    )
    # ### end Alembic commands ###
