"""Update migration to drop dependent constraints

Revision ID: 1564f9816a75
Revises: 0e1744db6833
Create Date: 2024-10-06 01:24:15.616009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1564f9816a75'
down_revision = '0e1744db6833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_factura')
    op.drop_table('gestion_clientes')
    op.drop_table('producto', cascade=True)
    op.drop_table('cliente')
    op.drop_table('factura')
    op.drop_table('detalle_factura')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.drop_column('cliente')

    with op.batch_alter_table('pre_facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.drop_column('cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    op.create_table('detalle_factura',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], name='detalle_factura_factura_id_fkey'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name='detalle_factura_producto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='detalle_factura_pkey')
    )
    op.create_table('factura',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('factura_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estatus', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='factura_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='factura_pkey'),
    sa.UniqueConstraint('numero', name='factura_numero_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cliente_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cliente_pkey'),
    sa.UniqueConstraint('email', name='cliente_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='producto_pkey')
    )
    op.create_table('gestion_clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gestion_clientes_pkey'),
    sa.UniqueConstraint('ruc', name='gestion_clientes_ruc_key')
    )
    op.create_table('item_factura',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], name='item_factura_factura_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_factura_pkey')
    )
    # ### end Alembic commands ###
