"""Update Invoice and Empresa models

Revision ID: 47e0867aa68a
Revises: 8251c0b31d8b
Create Date: 2024-09-24 01:16:46.437905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47e0867aa68a'
down_revision = '8251c0b31d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nombre', type_='unique')
        batch_op.create_unique_constraint(None, ['rnc'])

    with op.batch_alter_table('usuario_modulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_asignacion', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('usuario_modulo_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('usuario_modulo_modulo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modulos', ['modulo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_modulo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuario_modulo_modulo_id_fkey', 'modulos', ['modulo_id'], ['id'])
        batch_op.create_foreign_key('usuario_modulo_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('fecha_asignacion')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('unique_nombre', ['nombre'])

    op.create_table('historial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('accion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='historial_pkey')
    )
    # ### end Alembic commands ###
