"""Initial migration

Revision ID: 6581e43138ff
Revises: 3131d5d72cc7
Create Date: 2024-10-06 09:20:01.013547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6581e43138ff'
down_revision = '3131d5d72cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_factura', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])

    with op.batch_alter_table('items_pre_factura', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('documento_referencia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('documento_referencia')
        batch_op.drop_column('motivo')

    with op.batch_alter_table('items_pre_factura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('items_factura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
