"""Initial migration

Revision ID: a9cf58cc100b
Revises: 
Create Date: 2023-09-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a9cf58cc100b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))

    # Actualizar los registros existentes con valores predeterminados
    op.execute("UPDATE usuarios SET nombre = 'Nombre Pendiente' WHERE nombre IS NULL")
    op.execute("UPDATE usuarios SET apellido = 'Apellido Pendiente' WHERE apellido IS NULL")

    # Ahora podemos aplicar la restricción NOT NULL
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre', existing_type=sa.String(length=64), nullable=False)
        batch_op.alter_column('apellido', existing_type=sa.String(length=64), nullable=False)
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###