"""Cambiar cliente a proyecto_cliente

Revision ID: dcdc34e982a5
Revises: 2d89e45d2c5c
Create Date: 2024-10-20 21:56:13.545537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcdc34e982a5'
down_revision = '2d89e45d2c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas_debito_banco')
    # Comentamos la eliminación de la tabla empresa
    # op.drop_table('empresa')
    op.drop_table('admin_plan_suscripcion')
    op.drop_table('notas_credito_banco')
    op.drop_table('usuario_modulo_bot')
    op.drop_table('items')
    op.drop_table('inventarios_fisicos')
    op.drop_table('rol')
    op.drop_table('cuenta')
    op.drop_table('conversacion')
    op.drop_table('rol_bot')
    op.drop_table('contexto_asistente')
    op.drop_table('solicitud_compras')
    op.drop_table('nota_credito')
    op.drop_table('notificacion')
    op.drop_table('tipo_suplidor')
    op.drop_table('usuario')
    # Comentamos la eliminación de la tabla cliente
    # op.drop_table('cliente')
    with op.batch_alter_table('usuario_bot', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_bot_email')
        batch_op.drop_index('ix_usuario_bot_nombre_usuario')

    op.drop_table('usuario_bot')
    op.drop_table('admin_reporte')
    op.drop_table('modulo')
    op.drop_table('permiso')
    op.drop_table('detalles_inventario_fisico')
    op.drop_table('admin_configuracion_seguridad_bot')
    op.drop_table('admin_factura')
    op.drop_table('nota_debito')
    op.drop_table('requisicion_cotizacion')
    op.drop_table('pago_contado')
    op.drop_table('transaccion')
    op.drop_table('anticipo_cx_p')
    with op.batch_alter_table('empresa_bot', schema=None) as batch_op:
        batch_op.drop_index('ix_empresa_bot_nombre')

    op.drop_table('empresa_bot')
    op.drop_table('modulo_bot')

    # Crear la nueva tabla proyecto_cliente
    op.create_table('proyecto_cliente',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('ajustes_inventario', schema=None) as batch_op:
        batch_op.drop_constraint('ajustes_inventario_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items_inventario', ['item_id'], ['id'])

    with op.batch_alter_table('anticipo_cx_c', schema=None) as batch_op:
        batch_op.drop_constraint('anticipo_cx_c_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente_cxc', ['cliente_id'], ['id'])

    with op.batch_alter_table('asiento_diario', schema=None) as batch_op:
        batch_op.drop_constraint('asiento_diario_cuenta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contabilidad_cuentas', ['cuenta_id'], ['id'])

    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('bancos_nombre_key', type_='unique')
        batch_op.drop_constraint('bancos_telefono_key', type_='unique')
        batch_op.create_unique_constraint(None, ['codigo'])
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('telefono_contacto')
        batch_op.drop_column('contacto')
        batch_op.drop_column('telefono')
        batch_op.drop_column('estatus')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prospecto_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('campaign_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'prospecto', ['prospecto_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('conciliaciones', schema=None) as batch_op:
        batch_op.drop_constraint('conciliaciones_banco_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nuevo_bancos', ['banco_id'], ['id'])

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prospecto_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('contact_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'prospecto', ['prospecto_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cuenta_por_cobrar', schema=None) as batch_op:
        batch_op.drop_constraint('cuenta_por_cobrar_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente_cxc', ['cliente_id'], ['id'])

    with op.batch_alter_table('depositos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('concepto', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('estatus', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referencia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('creador', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('actualizado_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fuente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fuente_referencia', sa.String(length=50), nullable=True))
        batch_op.alter_column('divisa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('depositos_banco_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nuevo_bancos', ['banco_id'], ['id'])

    with op.batch_alter_table('factura_suplidor_cxp', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['numero_factura'])
        batch_op.drop_column('fecha_vencimiento')
        batch_op.drop_column('estado')
        batch_op.drop_column('fecha_emision')

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.alter_column('concepto',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('monto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('items_factura', schema=None) as batch_op:
        batch_op.drop_constraint('items_factura_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items_inventario', ['item_id'], ['id'])

    with op.batch_alter_table('items_pre_factura', schema=None) as batch_op:
        batch_op.drop_constraint('items_pre_factura_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items_inventario', ['item_id'], ['id'])

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_constraint('movimientos_inventario_nota_credito_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('movimientos_inventario_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('movimientos_inventario_factura_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items_inventario', ['item_id'], ['id'])
        batch_op.drop_column('factura_id')
        batch_op.drop_column('nota_credito_id')

    with op.batch_alter_table('nota_credito_cxp', schema=None) as batch_op:
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['numero'])
        batch_op.drop_constraint('nota_credito_cxp_factura_suplidor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'factura_suplidor_cxp', ['factura_id'], ['id'])
        batch_op.drop_column('factura_suplidor_id')

    with op.batch_alter_table('nota_debito_cxp', schema=None) as batch_op:
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['numero'])
        batch_op.drop_constraint('nota_debito_cxp_factura_suplidor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'factura_suplidor_cxp', ['factura_id'], ['id'])
        batch_op.drop_column('factura_suplidor_id')

    with op.batch_alter_table('nuevo_bancos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_index('idx_nuevo_bancos_codigo')
        batch_op.drop_index('idx_nuevo_bancos_codigo_swift')
        batch_op.drop_index('idx_nuevo_bancos_rnc')
        batch_op.drop_constraint('unique_rnc', type_='unique')
        batch_op.drop_column('rnc')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('fax')

    with op.batch_alter_table('orden_compra_cxp', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numero'])
        batch_op.drop_column('estado')

    with op.batch_alter_table('prospecto', schema=None) as batch_op:
        batch_op.drop_constraint('prospecto_empresa_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresa_marketing', ['empresa_id'], ['id'])

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto_cliente_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('proyecto_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'proyecto_cliente', ['proyecto_cliente_id'], ['id'])
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('suplidor_cxp', schema=None) as batch_op:
        batch_op.alter_column('ruc',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tipo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('suplidor_cxp_tipo_suplidor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_suplidor_cxp', ['tipo_id'], ['id'])
        batch_op.drop_column('tipo_suplidor_id')

    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('divisa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('transferencias_banco_origen_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transferencias_banco_destino_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nuevo_bancos', ['banco_destino_id'], ['id'])
        batch_op.create_foreign_key(None, 'nuevo_bancos', ['banco_origen_id'], ['id'])
        batch_op.create_foreign_key(None, 'divisas', ['divisa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transferencias_banco_destino_id_fkey', 'bancos', ['banco_destino_id'], ['id'])
        batch_op.create_foreign_key('transferencias_banco_origen_id_fkey', 'bancos', ['banco_origen_id'], ['id'])
        batch_op.drop_column('divisa_id')

    with op.batch_alter_table('suplidor_cxp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_suplidor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('suplidor_cxp_tipo_suplidor_id_fkey', 'tipo_suplidor', ['tipo_suplidor_id'], ['id'])
        batch_op.alter_column('tipo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ruc',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('proyecto_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])
        batch_op.drop_column('proyecto_cliente_id')

    with op.batch_alter_table('prospecto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prospecto_empresa_id_fkey', 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('orden_compra_cxp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('nuevo_bancos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fax', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rnc', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('unique_rnc', ['rnc'])
        batch_op.create_index('idx_nuevo_bancos_rnc', ['rnc'], unique=False)
        batch_op.create_index('idx_nuevo_bancos_codigo_swift', ['codigo_swift'], unique=False)
        batch_op.create_index('idx_nuevo_bancos_codigo', ['codigo'], unique=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('nota_debito_cxp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_suplidor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nota_debito_cxp_factura_suplidor_id_fkey', 'factura_suplidor_cxp', ['factura_suplidor_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('nota_credito_cxp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_suplidor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nota_credito_cxp_factura_suplidor_id_fkey', 'factura_suplidor_cxp', ['factura_suplidor_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_credito_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('movimientos_inventario_factura_id_fkey', 'facturacion', ['factura_id'], ['id'])
        batch_op.create_foreign_key('movimientos_inventario_item_id_fkey', 'items', ['item_id'], ['id'])
        batch_op.create_foreign_key('movimientos_inventario_nota_credito_id_fkey', 'notas_credito', ['nota_credito_id'], ['id'])

    with op.batch_alter_table('items_pre_factura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_pre_factura_item_id_fkey', 'items', ['item_id'], ['id'])

    with op.batch_alter_table('items_factura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_factura_item_id_fkey', 'items', ['item_id'], ['id'])

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('monto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('concepto',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('factura_suplidor_cxp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('depositos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('depositos_banco_id_fkey', 'bancos', ['banco_id'], ['id'])
        batch_op.alter_column('divisa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('fuente_referencia')
        batch_op.drop_column('fuente')
        batch_op.drop_column('actualizado_por')
        batch_op.drop_column('creador')
        batch_op.drop_column('referencia')
        batch_op.drop_column('estatus')
        batch_op.drop_column('concepto')
        batch_op.drop_column('numero')

    with op.batch_alter_table('cuenta_por_cobrar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cuenta_por_cobrar_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contact_user_id_fkey', 'usuario', ['user_id'], ['id'])
        batch_op.drop_column('prospecto_id')

    with op.batch_alter_table('conciliaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conciliaciones_banco_id_fkey', 'bancos', ['banco_id'], ['id'])

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('campaign_user_id_fkey', 'usuario', ['user_id'], ['id'])
        batch_op.drop_column('prospecto_id')

    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contacto', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono_contacto', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('bancos_telefono_key', ['telefono'])
        batch_op.create_unique_constraint('bancos_nombre_key', ['nombre'])
        batch_op.drop_column('codigo')

    with op.batch_alter_table('asiento_diario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asiento_diario_cuenta_id_fkey', 'cuenta', ['cuenta_id'], ['id'])

    with op.batch_alter_table('anticipo_cx_c', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('anticipo_cx_c_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('ajustes_inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ajustes_inventario_item_id_fkey', 'items', ['item_id'], ['id'])

    op.create_table('modulo_bot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='modulo_bot_pkey'),
    sa.UniqueConstraint('nombre', name='modulo_bot_nombre_key')
    )
    op.create_table('empresa_bot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('rnc', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='empresa_bot_pkey'),
    sa.UniqueConstraint('rnc', name='empresa_bot_rnc_key')
    )
    with op.batch_alter_table('empresa_bot', schema=None) as batch_op:
        batch_op.create_index('ix_empresa_bot_nombre', ['nombre'], unique=True)

    op.create_table('anticipo_cx_p',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suplidor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['suplidor_id'], ['suplidor_cxp.id'], name='anticipo_cx_p_suplidor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='anticipo_cx_p_pkey')
    )
    op.create_table('admin_plan_suscripcion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duracion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_plan_suscripcion_pkey')
    )
    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='empresa_pkey')
    )
    op.create_table('notas_debito_banco',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('banco_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], name='notas_debito_banco_banco_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notas_debito_banco_pkey')
    )
    # ### end Alembic commands ###