"""Add asistente_activo to Usuario

Revision ID: f7d4c763444f
Revises: 2cc508c55deb
Create Date: 2024-09-28 13:21:40.393085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d4c763444f'
down_revision = '2cc508c55deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('asistente_activo')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asistente_activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('asistente_activo')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asistente_activo', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
